{{- $root := . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ucentralgw.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ucentralgw.name" . }}
    helm.sh/chart: {{ include "ucentralgw.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ucentralgw.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.services.ucentralgw.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "ucentralgw.config" . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "ucentralgw.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.services.ucentralgw.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:

      containers:

        - name: ucentralgw
          image: "{{ .Values.images.ucentralgw.repository }}:{{ .Values.images.ucentralgw.tag }}"
          imagePullPolicy: {{ .Values.images.ucentralgw.pullPolicy }}

          command:
            - /ucentral/ucentralgw
            - --file=/ucentral-data/ucentral.properties

          env:
            - name: KUBERNETES_DEPLOYED
              value: "{{ now }}"
          {{- range $key, $value := .Values.public_env_variables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.secret_env_variables }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "ucentralgw.fullname" $root }}-env
                  key: {{ $key }}
          {{- end }}

          ports:
          {{- range $port, $portValue := .Values.services.ucentralgw.ports }}
            - name: {{ $port }}
              containerPort: {{ $portValue.targetPort }}
              protocol: {{ $portValue.protocol }}
          {{- end }}

          volumeMounts:
          {{- range .Values.volumes.ucentralgw }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}

          {{- if .Values.checks.ucentralgw.liveness }}
          livenessProbe:
            {{- toYaml .Values.checks.ucentralgw.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.checks.ucentralgw.readiness }}
          readinessProbe:
            {{- toYaml .Values.checks.ucentralgw.readiness | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      imagePullSecrets:
      {{- range $image, $imageValue := .Values.images }}
        {{- if $imageValue.regcred }}
      - name: {{ include "ucentralgw.fullname" $root }}-{{ $image }}-regcred
        {{- end }}
      {{- end }}

      volumes:
      {{- range $container, $containerVolumes := .Values.volumes }}
      {{- range $containerVolumes }}
      - name: {{ .name }}
        {{- tpl .volumeDefinition $root | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
